export const SAVE_PRODUCTS = "SAVE_PRODUCTS";
export const PRODUCTS_NOT_RESULTS = "PRODUCTS_NOT_RESULTS";
export const FILTER_SET = "FILTER_SET";
export const FILTER_SET_INIT = "FILTER_SET_INIT";

export const CLEAR_PRODUCTS_PROPIERTIES = "CLEAR_PRODUCTS_PROPIERTIES";
export const CART_SET = "CART_SET";
export const UPDATE_CART_ITEM = "UPDATE_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const SET_SHOPPING_ROUTE = "SET_SHOPPING_ROUTE";
export const SAVE_ORDER_DATA = "SAVE_ORDER_DATA";
export const SHOW_CART = "SHOW_CART";

export const OPEN_MODAL_ERROR = "OPEN_MODAL_ERROR";
export const CLOSE_MODAL_ERROR = "CLOSE_MODAL_ERROR";

export const RESET_CART = "RESET_CART";
export const RESET_PRODUCT = "RESET_PRODUCT";

export const SET_USER = "SET_USER";
export const RESET_USER = "RESET_USER";
export const SET_TOKEN = "SET_TOKEN";

export const SET_CURRENT_ROUTE = "SET_CURRENT_ROUTE";

export const SAVE_ORDERS = "SAVE_ORDERS";
export const ORDERS_NOT_RESULTS = "ORDERS_NOT_RESULTS";

export const RESET_ORDERS = "RESET_ORDERS";

export const SELECT_STATUS_ORDER = "SELECT_STATUS_ORDER";

export const SET_CART_STORAGE = "SET_CART_STORAGE";

export const DELETE_UPDATE_CART_ITEM = "DELETE_UPDATE_CART_ITEM";
